### ISSUE TITLE
Not working with Exchange 2016

### ISSUE THREAD

**Issue by L-C-P** [OfficeDev/Outlook-Add-in-JavaScript-MakeEWSRequest#1]
When running the demo, the asyncResult in callback contains the following error:
OSF.DDA.AsyncResult {value: null, status: "failed", error: OSF.DDA.Error}
error: OSF.DDA.Error
code: 9020
message: "Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden."
name: "GenericResponseError"

Any Ideas?

**Comment by jamescro** [comment]
Thanks for letting me know. I'll start looking into this and let you know if I can reproduce it.

**Comment by L-C-P** [comment]
Hi, i just found the problem: For my Exchange 2016 test, i setup my ad domain as: "sub.domain.de". So the host name is exchange.sub.domain.de. This is causing the problem. If i'm using "domain.de" everything works as expected.
So the topic is wrong and i think it's maybe more a problem of the https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js. But where i can address the problem?

**Comment by jamescro** [comment]
Could you send Fiddler traces for both the request and response? Also, when you say "the topic is wrong," are you referring to an MSDN topic? Could you provide a link to it?

**Comment by L-C-P** [comment]
Hi,

i thought, that the topic "Not working with Exchange 2016" is pointing into the wrong direction. So im not referring to some other topics. But let's skip this.

I attached the logs from the proxy.
The Translation for the error text in the response: The remotehost returns an error: (404) not found

[response.txt](https://github.com/OfficeDev/Outlook-Add-in-JavaScript-MakeEWSRequest/files/49633/response.txt)
[request.txt](https://github.com/OfficeDev/Outlook-Add-in-JavaScript-MakeEWSRequest/files/49634/request.txt)

**Comment by jamescro** [comment]
Thanks for the traces. Unfortunately, they don't tell us much more than we already know. The request looks good, so this appears to be an environmental issue. Do you know for sure that EWS is enabled? Can you make calls to it from your own backend?

**Comment by jamescro** [comment]
Without additional information, we can't investigate this further. Please re-open if you can provide the additional information requested or other pertinent information.
