### ISSUE TITLE
When exactly is OAuthAuthentication required on Exchabge side

### ISSUE THREAD

**Issue by ThorstenHans** [OfficeDev/Outlook-Add-in-JavaScript-MakeEWSRequest#2]
Hey, 

I've a similar app using just clientside code and the highest permission `ReadWriteMailbox` request available for Outlook Add-Ins.

The web itself is hosted somewhere (azure) and I want to use `office.context.mailbox.makeEwsRequestAsync`to receive the attachments from a mail by using GetItem SOAP request. 

The callback is invoked with status success but in the SOAP response a fault is listed saying that the method can not be executed by this client. 

The API reference mentions that OAuthAuthentication has to be activated on the exchange server, how can I achieve this in Office365? And how does this work when publishing the app to the public Office 365 store. To be honest, the documentation misses exactly those important details!

**Comment by jamescro** [comment]
Sorry it took us so long to respond. As I understand it you have a technical question about activating OAuth Authentication in Exchange. Please ask your question on stackoverflow.com. Tag your question 'office-js'.
